server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/veterano_local_db
    username: zdoryk
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
