server:
  port: 8086
spring:
  application:
    name: email
  mail:
    host: eushared15.twinservers.net
    password: 077214hyst*
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: info@hyst.site

  rabbitmq:
   addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


links:
  unsubscribe: http://45.94.157.117:8080/api/v1/subscription/unsubscribe?email=

