services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: veterano_local_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: zdoryk/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
  apigw:
    image: zdoryk/apigw:latest
    container_name: apigw
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
    depends_on:
      - eureka-server

  user:
    image: zdoryk/user:latest
    container_name: user
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - eureka-server
      - apigw

  auth:
    image: zdoryk/service-auth:latest
    container_name: auth
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
      - apigw

  email:
    image: zdoryk/service-email:latest
    container_name: email
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
      - apigw

  data:
    image: zdoryk/service-data:latest
    container_name: data
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
      - apigw

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: