server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/users/auth/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/credentials/**
          filters:
            - name: AuthFilter

        - id: card
          uri: lb://card
          predicates:
            - Path=/api/v1/**
          filters:
#            - name: AuthFilter


config:
  urls:
    validate-token: http://auth/api/v1/users/auth/validate-token?token=


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs

