server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        cors-configurations:
#          '[/**]':
#            allowedOrigins:
#              - "http://localhost:4200"
#              - "https://veterano-front.vercel.app/"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
#            allowCredentials: true

      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/users/auth/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/credentials/**
          filters:
#            - name: AuthFilter

        - id: data
          uri: lb://data
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthFilter



config:
  urls:
    validate-token: http://auth/api/v1/users/auth/validate-token?token=

security:
  jwt:
    token:
      secret-key: 923593859385983912541253261


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

