server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: data
  datasource:
    username: dev
    password: password
    url: jdbc:postgresql://localhost:5432/veterano_local_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

config:
  urls:
    approve-register: http://localhost:8080/api/v1/users/auth/approve-token?token=

security:
  jwt:
    token:
      secret-key: 923593859385983912541253261